import type { Metadata } from "next";

import CreatorsHeader from "@/components/layouts/creators-header";
import Footer from "@/components/layouts/footer";

export const metadata: Metadata = {
  title: "スリーネクストNFTミュージック クリエイターズエリア",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <CreatorsHeader />
      {children}
      <Footer />
    </>
  );
}
