// Code generated by MockGen. DO NOT EDIT.
// Source: business_gateway.go
//
// Generated by this command:
//
//	mockgen -package mock -source business_gateway.go -destination mock/business_gateway.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	domain "nft-music/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBusinessGateway is a mock of BusinessGateway interface.
type MockBusinessGateway struct {
	ctrl     *gomock.Controller
	recorder *MockBusinessGatewayMockRecorder
	isgomock struct{}
}

// MockBusinessGatewayMockRecorder is the mock recorder for MockBusinessGateway.
type MockBusinessGatewayMockRecorder struct {
	mock *MockBusinessGateway
}

// NewMockBusinessGateway creates a new mock instance.
func NewMockBusinessGateway(ctrl *gomock.Controller) *MockBusinessGateway {
	mock := &MockBusinessGateway{ctrl: ctrl}
	mock.recorder = &MockBusinessGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusinessGateway) EXPECT() *MockBusinessGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBusinessGateway) Create(ctx context.Context, business *domain.BusinessMaster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, business)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBusinessGatewayMockRecorder) Create(ctx, business any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBusinessGateway)(nil).Create), ctx, business)
}

// Delete mocks base method.
func (m *MockBusinessGateway) Delete(ctx context.Context, business *domain.BusinessMaster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, business)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBusinessGatewayMockRecorder) Delete(ctx, business any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBusinessGateway)(nil).Delete), ctx, business)
}

// Get mocks base method.
func (m *MockBusinessGateway) Get(ctx context.Context, id uuid.UUID) (*domain.BusinessMaster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.BusinessMaster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBusinessGatewayMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBusinessGateway)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockBusinessGateway) List(ctx context.Context) ([]domain.BusinessMaster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.BusinessMaster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBusinessGatewayMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBusinessGateway)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockBusinessGateway) Update(ctx context.Context, business *domain.BusinessMaster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, business)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBusinessGatewayMockRecorder) Update(ctx, business any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBusinessGateway)(nil).Update), ctx, business)
}
