// Code generated by MockGen. DO NOT EDIT.
// Source: collection_gateway.go
//
// Generated by this command:
//
//	mockgen -package mock -source collection_gateway.go -destination mock/collection_gateway.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	domain "nft-music/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCollectionGateway is a mock of CollectionGateway interface.
type MockCollectionGateway struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionGatewayMockRecorder
	isgomock struct{}
}

// MockCollectionGatewayMockRecorder is the mock recorder for MockCollectionGateway.
type MockCollectionGatewayMockRecorder struct {
	mock *MockCollectionGateway
}

// NewMockCollectionGateway creates a new mock instance.
func NewMockCollectionGateway(ctrl *gomock.Controller) *MockCollectionGateway {
	mock := &MockCollectionGateway{ctrl: ctrl}
	mock.recorder = &MockCollectionGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionGateway) EXPECT() *MockCollectionGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCollectionGateway) Create(ctx context.Context, collection *domain.Collection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, collection)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCollectionGatewayMockRecorder) Create(ctx, collection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCollectionGateway)(nil).Create), ctx, collection)
}

// Delete mocks base method.
func (m *MockCollectionGateway) Delete(ctx context.Context, collection *domain.Collection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, collection)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCollectionGatewayMockRecorder) Delete(ctx, collection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCollectionGateway)(nil).Delete), ctx, collection)
}

// Get mocks base method.
func (m *MockCollectionGateway) Get(ctx context.Context, id uuid.UUID) (*domain.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCollectionGatewayMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCollectionGateway)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockCollectionGateway) List(ctx context.Context) ([]domain.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCollectionGatewayMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCollectionGateway)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockCollectionGateway) Update(ctx context.Context, collection *domain.Collection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, collection)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCollectionGatewayMockRecorder) Update(ctx, collection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCollectionGateway)(nil).Update), ctx, collection)
}
