// Code generated by MockGen. DO NOT EDIT.
// Source: genre_gateway.go
//
// Generated by this command:
//
//	mockgen -package mock -source genre_gateway.go -destination mock/genre_gateway.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	domain "nft-music/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGenreGateway is a mock of GenreGateway interface.
type MockGenreGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGenreGatewayMockRecorder
	isgomock struct{}
}

// MockGenreGatewayMockRecorder is the mock recorder for MockGenreGateway.
type MockGenreGatewayMockRecorder struct {
	mock *MockGenreGateway
}

// NewMockGenreGateway creates a new mock instance.
func NewMockGenreGateway(ctrl *gomock.Controller) *MockGenreGateway {
	mock := &MockGenreGateway{ctrl: ctrl}
	mock.recorder = &MockGenreGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenreGateway) EXPECT() *MockGenreGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGenreGateway) Create(ctx context.Context, genre *domain.GenreMaster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, genre)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGenreGatewayMockRecorder) Create(ctx, genre any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGenreGateway)(nil).Create), ctx, genre)
}

// Delete mocks base method.
func (m *MockGenreGateway) Delete(ctx context.Context, genre *domain.GenreMaster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, genre)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGenreGatewayMockRecorder) Delete(ctx, genre any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGenreGateway)(nil).Delete), ctx, genre)
}

// Get mocks base method.
func (m *MockGenreGateway) Get(ctx context.Context, id uuid.UUID) (*domain.GenreMaster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.GenreMaster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGenreGatewayMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGenreGateway)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockGenreGateway) List(ctx context.Context) ([]domain.GenreMaster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.GenreMaster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGenreGatewayMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGenreGateway)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockGenreGateway) Update(ctx context.Context, genre *domain.GenreMaster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, genre)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGenreGatewayMockRecorder) Update(ctx, genre any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGenreGateway)(nil).Update), ctx, genre)
}
