// Code generated by MockGen. DO NOT EDIT.
// Source: ipfs_gateway.go

// Package mock is a generated GoMock package.
package mock

import (
	bytes "bytes"
	context "context"
	reflect "reflect"

	domain "nft-music/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockIpfsGateway is a mock of IpfsGateway interface.
type MockIpfsGateway struct {
	ctrl     *gomock.Controller
	recorder *MockIpfsGatewayMockRecorder
}

// MockIpfsGatewayMockRecorder is the mock recorder for MockIpfsGateway.
type MockIpfsGatewayMockRecorder struct {
	mock *MockIpfsGateway
}

// NewMockIpfsGateway creates a new mock instance.
func NewMockIpfsGateway(ctrl *gomock.Controller) *MockIpfsGateway {
	mock := &MockIpfsGateway{ctrl: ctrl}
	mock.recorder = &MockIpfsGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIpfsGateway) EXPECT() *MockIpfsGatewayMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockIpfsGateway) Add(ctx context.Context, body *bytes.Buffer, contentType string) (*domain.IpfsAdd, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, body, contentType)
	ret0, _ := ret[0].(*domain.IpfsAdd)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockIpfsGatewayMockRecorder) Add(ctx, body, contentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockIpfsGateway)(nil).Add), ctx, body, contentType)
}

// Get mocks base method.
func (m *MockIpfsGateway) Get(ctx context.Context, cid string) (*domain.IpfsJSON, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, cid)
	ret0, _ := ret[0].(*domain.IpfsJSON)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIpfsGatewayMockRecorder) Get(ctx, cid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIpfsGateway)(nil).Get), ctx, cid)
}

// Localpin mocks base method.
func (m *MockIpfsGateway) Localpin(ctx context.Context, cid string) (*domain.IpfsPins, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Localpin", ctx, cid)
	ret0, _ := ret[0].(*domain.IpfsPins)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Localpin indicates an expected call of Localpin.
func (mr *MockIpfsGatewayMockRecorder) Localpin(ctx, cid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Localpin", reflect.TypeOf((*MockIpfsGateway)(nil).Localpin), ctx, cid)
}

// Publish mocks base method.
func (m *MockIpfsGateway) Publish(ctx context.Context, cid string) (*domain.IpfsPublish, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, cid)
	ret0, _ := ret[0].(*domain.IpfsPublish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockIpfsGatewayMockRecorder) Publish(ctx, cid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockIpfsGateway)(nil).Publish), ctx, cid)
}

// Resolve mocks base method.
func (m *MockIpfsGateway) Resolve(ctx context.Context, name string) (*domain.IpfsResolve, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, name)
	ret0, _ := ret[0].(*domain.IpfsResolve)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockIpfsGatewayMockRecorder) Resolve(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockIpfsGateway)(nil).Resolve), ctx, name)
}
