// Code generated by MockGen. DO NOT EDIT.
// Source: transaction_gateway.go
//
// Generated by this command:
//
//	mockgen -package mock -source transaction_gateway.go -destination mock/transaction_gateway.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	domain "nft-music/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransactionGateway is a mock of TransactionGateway interface.
type MockTransactionGateway struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionGatewayMockRecorder
	isgomock struct{}
}

// MockTransactionGatewayMockRecorder is the mock recorder for MockTransactionGateway.
type MockTransactionGatewayMockRecorder struct {
	mock *MockTransactionGateway
}

// NewMockTransactionGateway creates a new mock instance.
func NewMockTransactionGateway(ctrl *gomock.Controller) *MockTransactionGateway {
	mock := &MockTransactionGateway{ctrl: ctrl}
	mock.recorder = &MockTransactionGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionGateway) EXPECT() *MockTransactionGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTransactionGateway) Create(ctx context.Context, transaction *domain.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTransactionGatewayMockRecorder) Create(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransactionGateway)(nil).Create), ctx, transaction)
}

// GetByTransactionid mocks base method.
func (m *MockTransactionGateway) GetByTransactionid(ctx context.Context, transactionID string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTransactionid", ctx, transactionID)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTransactionid indicates an expected call of GetByTransactionid.
func (mr *MockTransactionGatewayMockRecorder) GetByTransactionid(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTransactionid", reflect.TypeOf((*MockTransactionGateway)(nil).GetByTransactionid), ctx, transactionID)
}

// List mocks base method.
func (m *MockTransactionGateway) List(ctx context.Context, limit int) ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit)
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTransactionGatewayMockRecorder) List(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTransactionGateway)(nil).List), ctx, limit)
}

// ListByWallet mocks base method.
func (m *MockTransactionGateway) ListByWallet(ctx context.Context, wallet string) ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByWallet", ctx, wallet)
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByWallet indicates an expected call of ListByWallet.
func (mr *MockTransactionGatewayMockRecorder) ListByWallet(ctx, wallet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByWallet", reflect.TypeOf((*MockTransactionGateway)(nil).ListByWallet), ctx, wallet)
}

// Search mocks base method.
func (m *MockTransactionGateway) Search(ctx context.Context, genre string, minPrice, maxPrice int, sort string) ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, genre, minPrice, maxPrice, sort)
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockTransactionGatewayMockRecorder) Search(ctx, genre, minPrice, maxPrice, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockTransactionGateway)(nil).Search), ctx, genre, minPrice, maxPrice, sort)
}
