// Code generated by MockGen. DO NOT EDIT.
// Source: wallet_gateway.go
//
// Generated by this command:
//
//	mockgen -package mock -source wallet_gateway.go -destination mock/wallet_gateway.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	domain "nft-music/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWalletGateway is a mock of WalletGateway interface.
type MockWalletGateway struct {
	ctrl     *gomock.Controller
	recorder *MockWalletGatewayMockRecorder
	isgomock struct{}
}

// MockWalletGatewayMockRecorder is the mock recorder for MockWalletGateway.
type MockWalletGatewayMockRecorder struct {
	mock *MockWalletGateway
}

// NewMockWalletGateway creates a new mock instance.
func NewMockWalletGateway(ctrl *gomock.Controller) *MockWalletGateway {
	mock := &MockWalletGateway{ctrl: ctrl}
	mock.recorder = &MockWalletGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletGateway) EXPECT() *MockWalletGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWalletGateway) Create(ctx context.Context, wallet *domain.Wallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, wallet)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWalletGatewayMockRecorder) Create(ctx, wallet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWalletGateway)(nil).Create), ctx, wallet)
}

// Get mocks base method.
func (m *MockWalletGateway) Get(ctx context.Context, wallet *domain.Wallet) (*domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, wallet)
	ret0, _ := ret[0].(*domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWalletGatewayMockRecorder) Get(ctx, wallet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWalletGateway)(nil).Get), ctx, wallet)
}

// GetByID mocks base method.
func (m *MockWalletGateway) GetByID(ctx context.Context, wallet *domain.Wallet) (*domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, wallet)
	ret0, _ := ret[0].(*domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWalletGatewayMockRecorder) GetByID(ctx, wallet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWalletGateway)(nil).GetByID), ctx, wallet)
}

// List mocks base method.
func (m *MockWalletGateway) List(ctx context.Context) ([]domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWalletGatewayMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWalletGateway)(nil).List), ctx)
}
