// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "NFT Music",
            "url": "https://nft.threenext.com",
            "email": "seki@threenext.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/businesses": {
            "get": {
                "description": "職種マスターの情報をリストで取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "職種マスター"
                ],
                "summary": "職種マスターの情報をリストで取得する",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ports.BusinessMasterOutput"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            },
            "post": {
                "description": "職種マスターの情報を1件作成する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "職種マスター"
                ],
                "summary": "職種マスターの情報を1件作成する",
                "parameters": [
                    {
                        "description": "職種マスター",
                        "name": "wallet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ports.BusinessMasterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.BusinessMasterOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/businesses/{id}": {
            "get": {
                "description": "職種マスターの情報を出力し",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "職種マスター"
                ],
                "summary": "職種マスターから特定の１レコードを抽出する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "職種マスターID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.BusinessMasterOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            },
            "put": {
                "description": "職種マスターの情報を1件修正する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "職種マスター"
                ],
                "summary": "職種マスターの情報を1件修正する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "職種マスターID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "職種マスター",
                        "name": "wallet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ports.BusinessMasterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.BusinessMasterOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            },
            "delete": {
                "description": "職種マスターの情報を1件削除する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "職種マスター"
                ],
                "summary": "職種マスターの情報を1件削除する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "職種マスターID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.BusinessMasterOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/collections": {
            "get": {
                "description": "コレクションの情報をリストで取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "コレクション"
                ],
                "summary": "コレクションの情報をリストで取得する",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ports.CollectionOutput"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            },
            "post": {
                "description": "コレクションの情報を1件作成する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "コレクション"
                ],
                "summary": "コレクションの情報を1件作成する",
                "parameters": [
                    {
                        "description": "コレクション",
                        "name": "collection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ports.CollectionInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.CollectionOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/collections/{id}": {
            "get": {
                "description": "コレクションの情報を1件取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "コレクション"
                ],
                "summary": "コレクションの情報を1件取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "コレクションID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.CollectionOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            },
            "put": {
                "description": "コレクションの情報を1件修正する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "コレクション"
                ],
                "summary": "コレクションの情報を1件修正する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "コレクションID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "コレクション",
                        "name": "collection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ports.CollectionInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.CollectionOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            },
            "delete": {
                "description": "コレクションの情報を1件削除する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "コレクション"
                ],
                "summary": "コレクションの情報を1件削除する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "コレクションID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/evm": {
            "post": {
                "description": "Ethereum Virtual Machineのログイン情報を取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EVM"
                ],
                "summary": "EVMにログインを取得",
                "parameters": [
                    {
                        "description": "ウォレット",
                        "name": "wallet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ports.WalletInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.SignerOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/genres": {
            "get": {
                "description": "ジャンルマスターの情報をリストで取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ジャンルマスター"
                ],
                "summary": "ジャンルマスターの情報をリストで取得する",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ports.GenreMasterOutput"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            },
            "post": {
                "description": "ジャンルマスターの情報を1件作成する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ジャンルマスター"
                ],
                "summary": "ジャンルマスターの情報を1件作成する",
                "parameters": [
                    {
                        "description": "ジャンルマスター",
                        "name": "wallet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ports.GenreMasterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.GenreMasterOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/genres/{id}": {
            "get": {
                "description": "ジャンルマスターの情報を出力し",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ジャンルマスター"
                ],
                "summary": "ジャンルマスターから特定の１レコードを抽出する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ジャンルマスターID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.GenreMasterOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            },
            "put": {
                "description": "ジャンルマスターの情報を1件修正する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ジャンルマスター"
                ],
                "summary": "ジャンルマスターの情報を1件修正する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ジャンルマスターID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ジャンルマスター",
                        "name": "wallet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ports.GenreMasterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.GenreMasterOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            },
            "delete": {
                "description": "ジャンルマスターの情報を1件削除する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ジャンルマスター"
                ],
                "summary": "ジャンルマスターの情報を1件削除する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ジャンルマスターID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/ipfs": {
            "post": {
                "description": "分散型ストレージIPFSに画像を登録する",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPFS"
                ],
                "summary": "IPFSノードにイメージデータを登録",
                "parameters": [
                    {
                        "type": "file",
                        "description": "this is a test file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ウォレットアドレス",
                        "name": "wallet",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.IpfsOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/ipfs/meta": {
            "post": {
                "description": "分散型ストレージIPFSにJSONデータを登録する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPFS"
                ],
                "summary": "IPFSノードにJSONデータを登録",
                "parameters": [
                    {
                        "description": "MetaJSON",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ports.IpfsMetaInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.IpfsOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/nfts": {
            "get": {
                "description": "はブロックチェーンにNFTを複数出力する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT情報"
                ],
                "summary": "ブロックチェーンにNFTを複数出力する",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "取得件数",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ports.TransactionOutput"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            },
            "post": {
                "description": "NFTの情報をブロックチェーンに登録する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT情報"
                ],
                "summary": "NFTの情報をブロックチェーンに登録する",
                "parameters": [
                    {
                        "description": "ジャンルマスター",
                        "name": "wallet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ports.NftInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.TransactionOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/nfts/detail/{transaction_id}": {
            "get": {
                "description": "トランザクションIDに紐づくNFTを1件出力する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT情報"
                ],
                "summary": "トランザクションIDでNFTを1件出力する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "トランザクションID",
                        "name": "transaction_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.TransactionOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/nfts/search": {
            "get": {
                "description": "キーワードに一致するNFTを複数出力する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT情報"
                ],
                "summary": "キーワードでNFTを複数出力する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "検索キーワード",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ジャンルID",
                        "name": "genre",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最小価格",
                        "name": "min_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最大価格",
                        "name": "max_price",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ソート順",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ports.TransactionOutput"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/nfts/{wallet}": {
            "get": {
                "description": "ウォレットアドレスに紐づくNFTを複数出力する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT情報"
                ],
                "summary": "ウォレットアドレスでNFTを複数出力する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ウォレットアドレス",
                        "name": "wallet",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ports.TransactionOutput"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "NFTミュージックのアカウントを登録する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "アカウント"
                ],
                "summary": "NFTミュージックのアカウントを登録する",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ports.UserOutput"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            },
            "post": {
                "description": "NFTミュージックのアカウントを登録する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "アカウント"
                ],
                "summary": "NFTミュージックのアカウントを登録する",
                "parameters": [
                    {
                        "description": "ユーザー情報",
                        "name": "users",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ports.UserInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.UserOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/users/wallet/{wallet}": {
            "get": {
                "description": "ウォレットアドレスをキーにNFTミュージックのアカウント情報を取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "アカウント"
                ],
                "summary": "ウォレットアドレスからアカウント情報を取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ウォレットアドレス",
                        "name": "wallet",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.UserOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "NFTミュージックのアカウントを登録する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "アカウント"
                ],
                "summary": "NFTミュージックのアカウントを登録する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ユーザーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.UserOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            },
            "put": {
                "description": "NFTミュージックのアカウントの情報を変更する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "アカウント"
                ],
                "summary": "NFTミュージックのアカウントの情報を変更する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ユーザーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ユーザー情報",
                        "name": "users",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ports.UserInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.UserOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            },
            "delete": {
                "description": "NFTミュージックのアカウントを削除する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "アカウント"
                ],
                "summary": "NFTミュージックのアカウントを削除する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ユーザーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.UserOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        },
        "/wallets": {
            "get": {
                "description": "仮想通貨のウォレットの情報を出力する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ウォレット情報"
                ],
                "summary": "ウォレットの情報をデータベースから抽出する",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ports.WalletOutput"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            },
            "post": {
                "description": "ウォレットアドレスが登録されているかウォレットテーブルを確認し、なければウォレットアドレスをデータベースに格納する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ウォレット情報"
                ],
                "summary": "ウォレットアドレスをデータベースに格納する",
                "parameters": [
                    {
                        "description": "ウォレットアドレス",
                        "name": "wallet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ports.WalletInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ports.WalletOutput"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/ports.CreatedObject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ports.ErrorResponseObject"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ports.BusinessMasterInput": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "建築"
                }
            }
        },
        "ports.BusinessMasterOutput": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-11-04T20:51:26Z"
                },
                "id": {
                    "type": "string",
                    "example": "0193254c-a151-7c4c-b06a-259da7258a27"
                },
                "name": {
                    "type": "string",
                    "example": "建築"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-11-04T20:51:26Z"
                }
            }
        },
        "ports.CollectionInput": {
            "type": "object",
            "properties": {
                "banner_image_url": {
                    "type": "string",
                    "example": "https://www.yahoo.com/img/test.jpg"
                },
                "chain_id": {
                    "type": "integer",
                    "example": 1
                },
                "contract_address": {
                    "type": "string",
                    "example": "0x495f947276749ce646f68ac8c248420045075b34"
                },
                "description": {
                    "type": "string",
                    "example": "私はいつでも明るいです"
                },
                "external_url": {
                    "type": "string",
                    "example": "https://www.yahoo.com"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://www.yahoo.com/img/test.jpg"
                },
                "name": {
                    "type": "string",
                    "example": "建築"
                },
                "royalty": {
                    "type": "integer",
                    "example": 10
                },
                "royalty_receiver": {
                    "type": "string",
                    "example": "0x495f947276749ce646f68ac8c248420045075b34"
                },
                "user_id": {
                    "type": "string",
                    "example": "0193254c-a151-7c4c-b06a-259da7258a27"
                }
            }
        },
        "ports.CollectionOutput": {
            "type": "object",
            "properties": {
                "banner_image_url": {
                    "type": "string",
                    "example": "https://www.yahoo.com/img/test.jpg"
                },
                "chain_id": {
                    "type": "integer",
                    "example": 1
                },
                "contract_address": {
                    "type": "string",
                    "example": "0x495f947276749ce646f68ac8c248420045075b34"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-11-04T20:51:26Z"
                },
                "description": {
                    "type": "string",
                    "example": "私はいつでも明るいです"
                },
                "external_url": {
                    "type": "string",
                    "example": "https://www.yahoo.com"
                },
                "id": {
                    "type": "string",
                    "example": "0193254c-a151-7c4c-b06a-259da7258a27"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://www.yahoo.com/img/test.jpg"
                },
                "name": {
                    "type": "string",
                    "example": "建築"
                },
                "royalty": {
                    "type": "integer",
                    "example": 10
                },
                "royalty_receiver": {
                    "type": "string",
                    "example": "0x495f947276749ce646f68ac8c248420045075b34"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-11-04T20:51:26Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "0193254c-a151-7c4c-b06a-259da7258a27"
                }
            }
        },
        "ports.CreatedObject": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "01932564-3432-7b56-b772-7c69586e1897"
                },
                "message": {
                    "type": "string",
                    "example": "データベースには既に存在しています"
                },
                "status_code": {
                    "type": "integer",
                    "example": 201
                }
            }
        },
        "ports.ErrorResponseObject": {
            "type": "object",
            "properties": {
                "error_type": {
                    "type": "string",
                    "example": "リクエストの構文が不正やページが見つからない等のタイプ別"
                },
                "message": {
                    "type": "string",
                    "example": "原因となるのエラーメッセージ"
                },
                "status_code": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "ports.GenreMasterInput": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "エレクトロニック・ダンス・ミュージック"
                }
            }
        },
        "ports.GenreMasterOutput": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-11-04T20:51:26Z"
                },
                "id": {
                    "type": "string",
                    "example": "01932573-3f06-78c6-9743-b495cfcc2167"
                },
                "name": {
                    "type": "string",
                    "example": "エレクトロニック・ダンス・ミュージック"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-11-04T20:51:26Z"
                }
            }
        },
        "ports.IpfsMetaInput": {
            "type": "object",
            "required": [
                "audio_cid",
                "description",
                "file_type",
                "image_cid",
                "name",
                "video_cid"
            ],
            "properties": {
                "audio_cid": {
                    "type": "string",
                    "example": "QmPYVinZ3fmWSetwc9FWMF9b93hfKjWiHtygXfVY8exwEM"
                },
                "description": {
                    "type": "string",
                    "example": "良いNFTです"
                },
                "file_type": {
                    "type": "string",
                    "example": "audio"
                },
                "image_cid": {
                    "type": "string",
                    "example": "QmW9qWKbZneDijFPcHdbn41fQiHRwownM4U6avLsCHfMJS"
                },
                "insentive": {
                    "type": "integer",
                    "example": 10
                },
                "name": {
                    "type": "string",
                    "example": "GoodNFT"
                },
                "video_cid": {
                    "type": "string",
                    "example": "QmQfESxcop5u9zjvK5hJyX8oKJJZCsEYVh4kTU64Wzmxqz"
                }
            }
        },
        "ports.IpfsOutput": {
            "type": "object",
            "properties": {
                "cid": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "ports.NftInput": {
            "type": "object",
            "required": [
                "chain_id",
                "description",
                "genre_id",
                "insentive",
                "name",
                "price",
                "status",
                "wallet"
            ],
            "properties": {
                "audio_cid": {
                    "type": "string",
                    "example": "QmW9qWKbZneDijFPcHdbn41fQiHRwownM4U6avLsCHfMJS"
                },
                "chain_id": {
                    "type": "integer",
                    "example": 222
                },
                "description": {
                    "type": "string",
                    "example": "良いNFTです"
                },
                "file_type": {
                    "type": "string",
                    "example": "audio"
                },
                "genre_id": {
                    "type": "string",
                    "example": "019504e3-d996-7979-8043-ef03fa7a6d89"
                },
                "image_cid": {
                    "type": "string",
                    "example": "QmW9qWKbZneDijFPcHdbn41fQiHRwownM4U6avLsCHfMJS"
                },
                "insentive": {
                    "type": "string",
                    "example": "20"
                },
                "name": {
                    "type": "string",
                    "example": "GoodNFT"
                },
                "price": {
                    "type": "string",
                    "example": "1000.11"
                },
                "sale": {
                    "type": "boolean",
                    "example": false
                },
                "status": {
                    "type": "string",
                    "example": "mint"
                },
                "video_cid": {
                    "type": "string",
                    "example": "QmW9qWKbZneDijFPcHdbn41fQiHRwownM4U6avLsCHfMJS"
                },
                "wallet": {
                    "type": "string",
                    "example": "0xc5309Ef694C81C4a8e946F2810e09516436daeB5"
                }
            }
        },
        "ports.SignerOutput": {
            "type": "object",
            "properties": {
                "address_hex": {
                    "type": "string",
                    "example": "0x47CD2D0873833Ba015e0C31AB94D30313eF07942"
                },
                "transaction_hash": {
                    "type": "string",
                    "example": "0x9d605694113bde48dd07bf4d6f408906d3d5a9ee6656df600209ad6a38b2669e"
                }
            }
        },
        "ports.TransactionOutput": {
            "type": "object",
            "properties": {
                "audio_url": {
                    "type": "string"
                },
                "chain_id": {
                    "type": "integer"
                },
                "cost": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "file_type": {
                    "type": "string"
                },
                "genre_id": {
                    "type": "string"
                },
                "genre_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "insentive": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "nonce": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                },
                "sale": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "token_id": {
                    "type": "integer"
                },
                "token_url": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "video_url": {
                    "type": "string"
                }
            }
        },
        "ports.UserInput": {
            "type": "object",
            "required": [
                "email",
                "name",
                "wallet"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "東京都千代田区１−１−１"
                },
                "business_id": {
                    "type": "string",
                    "example": "019504de-f120-76af-905b-2fe06352b04a"
                },
                "email": {
                    "type": "string",
                    "example": "takeshi-kitagawa@gmail.com"
                },
                "eyecatch": {
                    "type": "string",
                    "example": "https://www.yahoo.com/img/test.jpg"
                },
                "face_image": {
                    "type": "string",
                    "example": "https://www.yahoo.com/img/test.jpg"
                },
                "name": {
                    "type": "string",
                    "example": "北川武"
                },
                "profile": {
                    "type": "string",
                    "maxLength": 4000,
                    "minLength": 10,
                    "example": "私はいつでも明るいです"
                },
                "role": {
                    "type": "string",
                    "example": "member"
                },
                "wallet": {
                    "type": "string",
                    "example": "0x411F8Cd035DB4874a8F1247Cb49908c794A0AB50"
                },
                "website": {
                    "type": "string",
                    "example": "https://www.yahoo.com"
                }
            }
        },
        "ports.UserOutput": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "東京都千代田区１−１−１"
                },
                "business_id": {
                    "type": "string",
                    "example": "019504de-f120-76af-905b-2fe06352b04a"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-11-04T20:51:26Z"
                },
                "email": {
                    "type": "string",
                    "example": "takeshi-kitagawa@gmail.com"
                },
                "eyecatch": {
                    "type": "string",
                    "example": "https://www.yahoo.com/img/test.jpg"
                },
                "face_image": {
                    "type": "string",
                    "example": "https://www.yahoo.com/img/test.jpg"
                },
                "id": {
                    "type": "string",
                    "example": "01932563-f671-71ff-9a0d-c452de9d06aa"
                },
                "name": {
                    "type": "string",
                    "example": "北川武"
                },
                "profile": {
                    "type": "string",
                    "example": "私はいつでも明るいです"
                },
                "role": {
                    "type": "string",
                    "example": "member"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-11-04T20:51:26Z"
                },
                "wallet": {
                    "type": "string",
                    "example": "01932564-3432-7b56-b772-7c69586e1897"
                },
                "website": {
                    "type": "string",
                    "example": "https://www.yahoo.com"
                }
            }
        },
        "ports.WalletInput": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0x29BE6Cd779c7ddbF6cBe3efdeF7Ba6f9CD2C703D"
                }
            }
        },
        "ports.WalletOutput": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0x85A4599940764d07f469EdEdAb10a72B727B6669"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-11-07T21:51:36Z"
                },
                "id": {
                    "type": "string",
                    "example": "01932550-9ecc-774f-b1ec-98d3002b9b2e"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
